### ISSUE TITLE
Question about: read -m fuses -f fuses.hex

### ISSUE THREAD

**Issue by a7hybnj2** [mraardvark/pymcuprog#2]
The output from `read -m fuses` and read -m fuses -f file.hex` seems to be very different. What is all the extra data in fuses.hex?

Also, I tried to `read -m fuses -f fuses.txt` and it was very unhappy about that.

```
cat pi/fuses.hex 
:02000004008278
:0A000000000002FF00C7030000FF2C
:00000001FF
```

**Comment by mraardvark** [comment]
Reading "to screen" (ie: no -f filename) uses the access granularity from device parameters to format the output, which is why reading flash and reading fuses may look different, for example.  When reading to file this display formatting is irrelevant, so the data is more "compact".  The extra data you see is the intelHex address and crc etc, the same as if your output was from Studio or MPLAB...
Specifying a .hex output will generate IntelHex format - all other files will be binary (ie no metadata at all)
